services:
  apache:
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV COMPOSER_ALLOW_SUPERUSER=1
  db:
    image: mysql:latest
    container_name: dbm
    ports:
      - '3307:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/mysql # Persist MySQL data

volumes:
  db_data: