services:
  apache:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:${DB_PASSWORD}@db/${DB_DATABASE}
    command: bash -c "composer install && php bin/console doctrine:s:u --force && ./startup.sh"

  db:
    image: mysql:latest
    container_name: db
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/mysql # Persist MySQL data

volumes:
  db_data: