services:
  apache:
    container_name: apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    command: ['php', '-S', '0.0.0.0:8000', 'public/index.php']
    depends_on:
      - db
    networks: 
    - local
    
  db:
    image: mysql:latest
    container_name: db
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    networks: 
    - local


networks:
  local:
    driver: bridge

volumes:
  db_data: