services:
  apache:
    container_name: apache
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
        - "9000:8000"
    volumes:
    - .:/var/www/html
  # db:
  #    image: mysql:latest
  #    container_name: dbm
  #    ports:
  #      - '3306:3306'  
  #    restart: always
  #    environment:
  #      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #      MYSQL_DATABASE: ${DB_DATABASE}
  #    volumes:
  #      - db_data:/var/lib/mysql  # Persist MySQL data

volumes:
  db_data: